#!/usr/bin/env bash
# Install and configures HAproxy on lb-01

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
server_config=\
"
frontend web-frontend
	mode http
	bind :80
	default_backend web-backend
backend web-backend
	mode http
	balance roundrobin
	server 419797-web-01 100.25.181.194:80 check
	server 419797-web-02 54.237.49.41:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling HAproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
