#!/usr/bin/env bash
# Installing and Configuring nginx on port 80
sudo apt-get -y install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
