#!/usr/bin/env bash
#This script displays numbers from 1 to 100
for ((i = 1; i <= 100; i++))
do
	if [ $((i % 5)) -eq 0 ]; then
		if [ $((i % 3)) -eq 0 ]; then
			echo "FizzBuzz"
		else
			echo "Buzz"
		fi
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi
done
